// packages/react-app/src/components/stateless/list-item/list-item.tsx
import { FC } from 'react'

import '@material/web/list/list-item'

import { ListItemProps } from './types'

export const ListItem: FC<ListItemProps> = ({ title, content }) => {
  return (
    <md-list-item>
      <div className='list-item__headline' slot='headline'>
        {title}
      </div>
      <div slot='supporting-text'>{content}</div>
    </md-list-item>
  )
}

// packages/vue-app/src/components/stateless/list/list-item.vue
<script setup lang="ts">
  import '@material/web/list/list-item'

  defineProps<{
    title: string
    content: string
  }>()
</script>

<template>
  <md-list-item>
    <div class="list-item__headline" slot="headline">
      {{ title }}
    </div>
    <div slot="supporting-text">
      {{ content }}
    </div>
  </md-list-item>
</template>
